[phases.setup]
nixPkgs = ["php81"]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php",
  "chmod +x composer.phar",
  "mv composer.phar /usr/bin/composer",
  "cd becraft && /usr/bin/composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "cd becraft && php artisan serve --host=0.0.0.0 --port=$PORT"
