
[phases.setup]
nixPkgs = ["php81", "curl"]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php",
  "chmod +x composer.phar",
  "mv composer.phar /usr/bin/composer",
  "cd becraft && composer install --no-dev --optimize-autoloader && php artisan config:cache"
]

[start]
cmd = "cd becraft && php -d variables_order=EGPCS -S 0.0.0.0:$PORT -t public"
